### ISSUE TITLE
tomcat-core artifacts missing from Maven Central

### ISSUE THREAD

**Issue by bkoehm** [hazelcast/hazelcast-tomcat-sessionmanager#36] opened 2017-12-08 16:04 UTC
http://central.maven.org/maven2/com/hazelcast/hazelcast-tomcat-sessionmanager/1.1.2/ is present, but the tomcat-core dependencies are missing in central.maven.org.

**Comment by mesutcelik** [comment] 2017-12-08 16:50
Hi @bkoehm ,
We do create uberJar including `tomcat-core` so those jars would work fine. Have you had any issue?

**Comment by mesutcelik** [comment] 2018-04-27 13:33
closing this one. please send your further questions to https://groups.google.com/forum/#!forum/hazelcast

**Comment by anton-johansson** [comment] 2018-06-18 09:11
Is the uberJar available from Maven Central? One could think that [this](http://mvnrepository.com/artifact/com.hazelcast/hazelcast-tomcat8-sessionmanager/1.1.3) is the uberJar for Tomcat 8, but it is not. It also has a dependency (tomcat-core) which does not exist, which can cause some really unnecessary headache for users (us). I believe this is the same issue that @bkoehm had. Why is the broken artifact deployed to Maven? And how can I find the uberJar in Maven Central?

**Comment by emre-aydin** [comment] 2018-06-18 09:19
Hi @anton-johansson 

The artifact is not broken. This is not an uberJar. As you've said, it has a dependency on `tomcat-core`. Since the JARs are to be put under Tomcat directory manually, we mostly focused on putting it under GitHub releases tab. You can download `tomcat-core` from the GitHub releases tab (https://github.com/hazelcast/hazelcast-tomcat-sessionmanager/releases). 

I agree with making it more user friendly for people using it via Maven though, so I'm reopening the issue. I believe it will be a simple fix to deploy `tomcat-core` artifact to Maven central. We might also consider having all versions of the JARs as uber JARs which would further simplify deployment, both manual and via Maven.

**Comment by emre-aydin** [comment] 2018-06-18 09:31
@anton-johansson I think I understand the cause of confusion better now. The artifact is indeed an uber JAR but its `pom.xml` is incorrect as it lists `tomcat-core` as one of its dependencies. So the JAR is OK, but the `pom.xml` is incorrect.

**Comment by anton-johansson** [comment] 2018-06-18 10:00
Allright. Since you can't overwrite artifacts in Central, I assume we'll wait for the next release. :)

An alternative would be to deploy empty `tomcat-core` artifacts, one for each "broken" version.

**Comment by emre-aydin** [comment] 2018-06-18 10:03
@mesutcelik suggested that you might try excluding the `tomcat-core` dependency from `hazelcast-tomcat-session-manager` dep. in your `pom.xml` until then.

**Comment by anton-johansson** [comment] 2018-06-18 10:04
Ahh, of course, that should work. Thanks!

**Closed** 2020-04-21 09:09 UTC
Labels: enhancement
